### PR TITLE
Remove wrapper

### PR DESCRIPTION
**Pull request by luca-bellenghi**
This is a quite large change.
We notice it's impossible to use layout where tile should fill just a portion of the page (like 1, 3, 1/3, 1/3 or 1/2, 1/2).
In this way we remove the tileWrapper from the tiles_view. We need to add it in every single tile, but in this way we can use class like halfWidth or similar and via css manage the layout.

We also add a parameter to the tiles-manager pattern: now you can use useModal:false to avoid modal windows when use tiles... This is useful only in project where people customize tile add/edit view...

### CODE REVIEW

**Comment by nzambello** [comment]
Any update here? What is the situation?
BTW: when we'll rebase this onto master, the CI will probably success.

**Comment by nzambello** [comment]
I have to check diffs from 0b956b5.
In the worst case, I'll revert this deleting that commit.

I merged `master` into `remove_wrapper` because I wanted a merge-ready branch and there were too many conflicts to do a clean rebase.

I noticed that edit buttons aren't shown, I'll investigate.

**Comment by cekk** [comment]
this entire pr need to be refactored, to work properly with every possible tile (not only ours).
It assumes that every tile exposes its id.

**Comment by nzambello** [comment]
Closing this.
If the `addModal` is a requested feature, open another PR with it.

The removal of the wrapper is not the way we want to follow for size handling, now is presented a different solution with a new UI in  #12

**Pull request closed without merging**
